package com.lambdaschool.countries.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * The country's data
 */
@Entity
@Table(name = "countries")
public class Country
{
    /**
     * The id (long) of a country object. Unique to all countries
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long countryid;

    /**
     * The name (String) of the country
     */
    private String name;

    /**
     * The population (long) of the country
     */
    private long population;

    /**
     * The land mass (long) of the country in Kilometers Squared (km2)
     */
    private long landmasskm2;

    /**
     * The median age (int) of the country
     */
    private int medianage;

    /**
     * Given the parameters, create new country object
     * <p>
     * id is autogenerated
     *
     * @param name       The name (String) of the country
     * @param population The population (long) of the country
     * @param landmasskm2   The land mass (long) of the country in Kilometers Squared (km2)
     * @param medianage  The median age (int) of the country
     */
    public Country(String name,
                   long population,
                   long landmasskm2,
                   int medianage)
    {
        this.name = name;
        this.population = population;
        this.landmasskm2 = landmasskm2;
        this.medianage = medianage;
    }

    /**
     * The default constructor required by Spring Data JPA
     */
    public Country()
    {
    }

    /**
     * Getter for country id
     *
     * @return country id (long) for this country
     */
    public long getCountryid()
    {
        return countryid;
    }

    /**
     * Setter for country id
     *
     * @param countryid make this country's id the one from the paramter
     */
    public void setCountryid(long countryid)
    {
        this.countryid = countryid;
    }

    /**
     * Getter for name
     *
     * @return name (String) of the country
     */
    public String getName()
    {
        return name;
    }

    /**
     * Setter for name
     *
     * @param name the new name (String) for the country
     */
    public void setName(String name)
    {
        this.name = name;
    }

    /**
     * Getter for population
     *
     * @return returns the population (long) of the country
     */
    public long getPopulation()
    {
        return population;
    }

    /**
     * Setter for population
     *
     * @param population the new population (long) of the country
     */
    public void setPopulation(long population)
    {
        this.population = population;
    }

    /**
     * Getter for land mass
     *
     * @return the land mass (long) in km2 of the country
     */
    public long getLandmasskm2()
    {
        return landmasskm2;
    }

    /**
     * Setter for land mass
     *
     * @param landmasskm2 the new land mass (long) in km2 of the country
     */
    public void setLandmasskm2(long landmasskm2)
    {
        this.landmasskm2 = landmasskm2;
    }

    /**
     * Getter for median age
     *
     * @return the median age (int) of the country
     */
    public int getMedianage()
    {
        return medianage;
    }

    /**
     * Setter for median age
     *
     * @param medianage the new median age (int) of the country
     */
    public void setMedianage(int medianage)
    {
        this.medianage = medianage;
    }
}
